### ISSUE TITLE
Also read engine from configuration file (`_quarto.yml`)

### ISSUE THREAD

**Issue by kellertuer** [PumasAI/QuartoNotebookRunner.jl#90] opened 2024-04-10 16:13 UTC
I just tried this new runner on the dev version of the quarto cli – and in general it works fine, but I noticed one thing that might be a bug.

here is my example: Take

* this tutorial https://github.com/JuliaManifolds/Manopt.jl/blob/master/tutorials/Optimize.qmd
* which uses this configuration https://github.com/JuliaManifolds/Manopt.jl/blob/master/tutorials/_quarto.yml

When I do

1. a line `engine: Julia` as an additional line after line 3 in the file and running `quarto render Optimise.qmd` on that folder, it is much faster than the Jupyter variant (which is great) and produces the same result. the result even ends up in the right folder (as specified in the config, somewhere in the docs)

but when

2. I add that line `engine: Julia`  to the end of the config (with or without removoing the statement that Jupyter prefers to use 1.10) the rendering is still happening with Jupyter,

The way one can nicely distinguish both runners, ist that this runner displays the first code line of cells it runs, while the Jupyter does not do that. So the second is really running on Jupyter still.

So:

Is that a bug or did I miss something? I would prefer to specify the runner only once for all my notebooks; though 10 is not too many, if I can reduce the amount of copied setups, that would be great.

Besides that the test run with 1. worked great and I am looking forward having that in a next version of quarto 👍

**Comment by jkrumbiegel** [comment] 2024-04-10 17:05
Probably the key ends up in a different location than where we're looking if it's set via `_quarto.yml`. The structure that quarto creates out of all the merged options is a little confusing.

**Comment by kellertuer** [comment] 2024-04-10 17:33
Ah yes it is `julia`, that was really just my autocorrect when I typed it here, sorry for not noticing that. I of course did the test with the lower letter word.

**Comment by jkrumbiegel** [comment] 2024-04-15 10:24
@kellertuer thinking about it some more, this is actually not a QuartoNotebookRunner bug, the problem is on the quarto side. Our engine is not being invoked by quarto because it probably only checks for the `engine` key on the file level, but not the project level. I suggest you open an issue over there :)

**Closed** 2024-04-15 10:24 UTC

**Comment by kellertuer** [comment] 2024-04-15 10:50
hm, to be honest, my experience with Quarto itself is, that even when I open a PR there is nothing happening for a few years usually. So reporting it there to me seems useless from my current experiences.

**Comment by jkrumbiegel** [comment] 2024-04-15 12:36
I've done it for you now

**Comment by kellertuer** [comment] 2024-04-15 15:23
Thanks, but well it shows, how much they (positively phrased as possible) find time or have the ability to fix bugs, when that bug is already known since 2022.
